## Tensors in Pytorch

Adapted from notebook `02_Tensors` by Joe Papa

Tensors are the main data format for Pytorch deep learning, and they are essentially the same as `numpy` arrays, and support the same kinds of operations, with a couple of notable exceptions:

1. Sometimes functions have slightly a different syntax (e.g., <code>np.zeros((2,5))</code> vs. <code>torch.zeros(2,5)</code>.
2. Tensors can represent scalars directly (not just via a one-element array)
3. Tensors can keep track of changes to facilitate back-propagation (we won't have to worry about this)
4. Tensors facilitate parallel computation when they are stored on a GPU

# Creating Tensors

Tensors are mostly the same as numpy arrays. For almost all your applications, tensors will hold floats.

In [1]:
import numpy as np

x = np.array([1,2,3])
print(x)
print()

y = np.ones((2,5))
print(y)


[1 2 3]

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [2]:
import torch

# Created from pre-existing arrays
w = torch.tensor([1,2,3])              # from a list
w = torch.tensor((1,2,3))              # from a tuple
w = torch.tensor(x)                    # from a numpy array
print(w)
print()

# Initialized by size
w = torch.empty(2,5)         # uninitialized, elements values are not predictable
w = torch.empty((2,5))       # can use same syntax as with numpy
w = torch.zeros((2,5))        # all elements initialized with 0.0
w = torch.ones(2,5)          # all elements initialized with 0.0
print(w)
print()

# Initialized with same shape and type as another tensor, but with potentially different contents.
w = torch.zeros_like(w)
print(w)
print()

# Initialized by size with random values
w = torch.rand(5,10)             # Creates a 100 x 200 tensor from a uniform distribution on [0, 1)
print(w)
print()

w = torch.randn(5,10)            # Same but from a standard normal distribution
w = torch.randint(0,10,(5,10))   # Same from uniformly choosen from [0,1,3,4,5,6,7,8,9]
print(w)

tensor([1, 2, 3])

tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]])

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])

tensor([[0.6924, 0.9653, 0.8391, 0.0475, 0.4451, 0.5401, 0.6464, 0.1467, 0.6108,
         0.1003],
        [0.2230, 0.3137, 0.5818, 0.7473, 0.3101, 0.2594, 0.9429, 0.4071, 0.9972,
         0.8877],
        [0.5655, 0.6921, 0.5836, 0.5450, 0.4879, 0.0840, 0.5243, 0.6857, 0.5096,
         0.7114],
        [0.7891, 0.2992, 0.4450, 0.4153, 0.1395, 0.8298, 0.7646, 0.8859, 0.6523,
         0.8076],
        [0.8990, 0.3842, 0.6025, 0.4057, 0.1272, 0.6045, 0.8039, 0.8829, 0.3003,
         0.3251]])

tensor([[0, 4, 3, 8, 0, 1, 9, 5, 7, 2],
        [4, 3, 7, 7, 3, 9, 0, 5, 1, 1],
        [2, 6, 8, 8, 2, 6, 9, 1, 9, 5],
        [7, 7, 9, 3, 8, 0, 8, 9, 6, 1],
        [3, 2, 3, 8, 7, 5, 4, 9, 1, 0]])


Exploring the attributes of a tensor is similar to numpy:

In [4]:
print(w.shape)
print(w.size())
print(w.dtype)
print(w.ndim)      # how many dimensions

torch.Size([5, 10])
torch.Size([5, 10])
torch.int64
2


As mentioned, tensors can also hold scalar values in a way that is consistent with array data

In [5]:
x = torch.tensor(10)          #  This is the constructor
print(x)
print()

y = 2 * x                     #  You can do ordinary arithmetic on tensors
print(y)
print()

print(x*x)
print()

print( x.item() )             #  This is how to extract the numeric value.

tensor(10)

tensor(20)

tensor(100)

10


## Data Types

In [6]:
# Specify data type at creation using dtype
w = torch.tensor([1,2,3], dtype=torch.float32)

# Use casting method to cast to a new data type
w.int()       # w remains a float32 after cast
w = w.int()   # w changes to int32 after cast

# Use to() method to cast to a new type
w = w.to(torch.float64) # <1>
w = w.to(dtype=torch.float64) # <2>

# Python automatically converts data types during operations
x = torch.tensor([1,2,3], dtype=torch.int32)
y = torch.tensor([1,2,3], dtype=torch.float32)
z = x + y                                       # x is converted to float32 before adding

print(z.dtype)

torch.float32


## Tensor Operations: indexing, slicing, transposing, and aggregating

These are essentially the same as with numpy.

In [7]:
x = torch.tensor([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
print(x)
print()

# Indexing, returns a tensor
print(x[1,1])
print()

# Indexing, returns value as Python number
print(x[1,1].item())
print()

# Slicing
print(x[:2,1])
print()

print(x[:-1,:])
print()

# Boolean indexing:  Only keep elements less than 5
print(x[x<5])
print()



tensor([[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12]])

tensor(5)

5

tensor([2, 5])

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

tensor([1, 2, 3, 4])



In [8]:
# Transpose array, x.t() or x.T can be used
print(x.t())
print()

# Changing shape, Usually view() is preferred over reshape()
print(x.view((2,6)))   # must have the same number of elements
print()

print(x)                      # does not change shape of original, so assign if you want a new shape
print()

# flattening tensors
a = x.flatten()
print(a)
print()

print(x.view(12))   # another way to do it
print()

print(x.view(-1))   # weird, but you'll see this too:
print()



tensor([[ 1,  4,  7, 10],
        [ 2,  5,  8, 11],
        [ 3,  6,  9, 12]])

tensor([[ 1,  2,  3,  4,  5,  6],
        [ 7,  8,  9, 10, 11, 12]])

tensor([[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12]])

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])



In [9]:
# Combining tensors
y = torch.stack((x, x))
print(y)
print()

z = torch.hstack((x, x))
print(z)
print()

# Splitting tensors
a,b,c,d = x.unbind(dim=0)
print(a,b,c,d)
print()
a,b,c = x.unbind(dim=1)
print(a,b,c)
print()


tensor([[[ 1,  2,  3],
         [ 4,  5,  6],
         [ 7,  8,  9],
         [10, 11, 12]],

        [[ 1,  2,  3],
         [ 4,  5,  6],
         [ 7,  8,  9],
         [10, 11, 12]]])

tensor([[ 1,  2,  3,  1,  2,  3],
        [ 4,  5,  6,  4,  5,  6],
        [ 7,  8,  9,  7,  8,  9],
        [10, 11, 12, 10, 11, 12]])

tensor([1, 2, 3]) tensor([4, 5, 6]) tensor([7, 8, 9]) tensor([10, 11, 12])

tensor([ 1,  4,  7, 10]) tensor([ 2,  5,  8, 11]) tensor([ 3,  6,  9, 12])



## Devices:  CPU

If you do nothing, all your data will be stored in your cpu's memory.

In [10]:
import torch

x = torch.tensor([[1,2,3],[4,5,6]])
y = torch.tensor([[7,8,9],[10,11,12]])
z = x + y
print(z)

print(z.device)     # each tensor has an attribute telling where it is stored

tensor([[ 8, 10, 12],
        [14, 16, 18]])
cpu


## Devices: GPU

In [11]:
# standard way to assign a GPU if is available (e.g., on Collab)

device = "cuda" if torch.cuda.is_available() else "cpu"

print(f"Using {device}")
print()

x = torch.tensor([[1,2,3],[4,5,6]   ], device=device)   # you can specify a device in a constructor
y = torch.tensor([[7,8,9],[10,11,12]], device=device)
z = x + y
print(z)
print()
print(z.size())
print()
print(z.device)
print()

Using cuda

tensor([[ 8, 10, 12],
        [14, 16, 18]], device='cuda:0')

torch.Size([2, 3])

cuda:0



## Moving Tensors between CPU & GPU

You can NOT perform arithmetic when operands are in different devices. So you will have to move
data back and forth sometimes (e.g., you want to do batch computations on the GPU but otherwise
use your local cpu).

You can print out data from the GPU, however!

In [12]:
device = "cuda" if torch.cuda.is_available() else "cpu"
print(f"Using {device}")
print()

x = torch.tensor([[1,2,3],[4,5,6]   ],device=device)   # you can specify a device in a constructor
y = torch.tensor([[7,8,9],[10,11,12]])

print(x.device, y.device)

z = x + y



Using cuda

cuda:0 cpu


RuntimeError: ignored

In [13]:
# you can convert to a new device temporarily

z = x + y.to(device)

print(x.device, y.device)

# or permanently

y = y.to(device)                 # remember to reassign it, otherwise the device is not changed

print(x.device, y.device)

z = x + y

print(z)

print(z.to('cpu'))


cuda:0 cpu
cuda:0 cuda:0
tensor([[ 8, 10, 12],
        [14, 16, 18]], device='cuda:0')
tensor([[ 8, 10, 12],
        [14, 16, 18]])
